/**
 * 
 */
package com.jci.alex.generator;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * @author YXIN1
 *
 */
public class A_Header
{
	private String Content="";
	public A_Header(String PXA_name)
	{
		Content+="#ifndef I_PREFAB_" + PXA_name.toUpperCase();
		Content+="\n";
		Content+="#define I_PREFAB_" + PXA_name.toUpperCase();
		Content+="\n";
		Content+=
				"// *********************************************************************************************************************";
		Content+="\n";
		Content+=
				"//*                                                                                                                    *";
		Content+="\n";
		Content+=
				"//*                                          CONFIDENTIAL VISTEON CORPORATION                                          *";
		Content+="\n";
		Content+=
				"//*                                                                                                                    *";
		Content+="\n";
		Content+=
				"//* This is an unpublished work of authorship, which contains trade secrets, created in 2014. Visteon Corporation      *";
		Content+="\n";
		Content+=
				"//* owns all rights to this work and intends to maintain it in confidence to preserve its trade secret status.         *";
		Content+="\n";
		Content+=
				"//* Visteon Corporation reserves the right, under the copyright laws of the United States or those of any other        *";
		Content+="\n";
		Content+=
				"//* country that may have jurisdiction, to protect this work as an unpublished work, in the event of an inadvertent    *";
		Content+="\n";
		Content+=
				"//* or deliberate unauthorized publication. Visteon Corporation also reserves its rights under all copyright laws      *";
		Content+="\n";
		Content+=
				"//* to protect this work as a published work, when appropriate. Those having access to this work may not copy it,      *";
		Content+="\n";
		Content+=
				"//* use it, modify it or disclose the information contained in it without the written authorization of                 *";
		Content+="\n";
		Content+=
				"//* Visteon Corporation.                                                                                               *";
		Content+="\n";
		Content+=
				"//*                                                                                                                    *";
		Content+="\n";
		Content+=
				"// *********************************************************************************************************************";
		Content+="\n";
		Content+="// Language:            CPP";
		Content+="\n";
		Content+=
				"// ---------------------------------------------------------------------------------------------------------------------";
		Content+="\n";
		Content+=
				"//				      DO NOT CHANGE THIS FILE! IT HAS BEEN GENERATED. ANY CHANGES WILL BE OVERWRITTEN AT THE NEXT GENERATION!";
		Content+="\n";
		Content+=
				"// ---------------------------------------------------------------------------------------------------------------------";
		Content+="\n";
		Content+="// Generated by the VISTEON PXA Generation chain ";
		Content+="\n";
		Content+=
				"// ---------------------------------------------------------------------------------------------------------------------";
		Content+="\n";
		Content+="// Input file:          " + PXA_name + ".pxa";
		Content+="\n";
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Date date = new Date();
		Content+="// Input file date:        " + dateFormat.format(date);
		Content+="\n";
		Content+=
				"// ---------------------------------------------------------------------------------------------------------------------";
		Content+="\n";
		Content+="// Generator version:   " + Z_DataStructure.GeneratorVersion;
		Content+="\n";
		Content+="// Generator date:      " + dateFormat.format(date);
		Content+="\n";
		Content+=
				"// *********************************************************************************************************************";
		Content+="\n";
	}
	
	
	public String getContent()
	{
		return Content;
	}
}
